// Copyright (c) 2023-2026 Chris Pulman and Contributors. All rights reserved.
// Chris Pulman and Contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Windows.Threading;
using ReactiveListTestApp.Models;
using TUnit.Core.Executors;

namespace ReactiveListTestApp.Tests;

/// <summary>Verifies dispatcher projections and user commands with the producer paused.</summary>
[STAThreadExecutor]
[Culture("en-US")]
public sealed class MainWindowViewModelTests
{
    /// <summary>The number of projected instruments and matrix cells.</summary>
    private const int InstrumentCount = 40;

    /// <summary>The number of available feature cards and instruments per matrix row.</summary>
    private const int RowWidth = 10;

    /// <summary>The number of sector groups.</summary>
    private const int SectorCount = 5;

    /// <summary>The rate assigned when the view model is constructed.</summary>
    private const int DefaultRate = 10_000;

    /// <summary>The rate yielding one thousand raw events per step.</summary>
    private const int StepRate = 8_000;

    /// <summary>The raw event count generated by each step or low-rate burst.</summary>
    private const int RawFrameCount = 1_000;

    /// <summary>The number of pause toggles used to verify notifications.</summary>
    private const int ToggleCount = 3;

    /// <summary>The retained tape bound.</summary>
    private const int TapeLimit = 800;

    /// <summary>The largest indexed history after trimming whole frames.</summary>
    private const int IndexedLimit = 1_240;

    /// <summary>The diagnostic stream retention bound.</summary>
    private const int StreamLimit = 160;

    /// <summary>The number of bursts needed to cross both history bounds.</summary>
    private const int BurstCount = 35;

    /// <summary>Exposes the venue matrix, feature catalog and initially running commands.</summary>
    /// <returns>A task representing the asynchronous test.</returns>
    [Test]
    public async Task Constructor_InitialState_ExposesShowcase()
    {
        using var model = new MainWindowViewModel(new FixedTimeProvider());
        var running = model.IsRunning;
        var startText = model.StartPauseText;
        var canStep = model.StepCommand.CanExecute(null);
        model.StartPauseCommand.Execute(null);
        await Assert.That(running).IsTrue();
        await Assert.That(startText).IsEqualTo("Pause");
        await Assert.That(canStep).IsFalse();
        await Assert.That(model.MatrixCellCount).IsEqualTo(InstrumentCount);
        await Assert.That(Array.ConvertAll(ReadItems<MatrixRow>(model.MatrixRows), static row => row.Lane))
            .IsEquivalentTo(model.Venues);
        var cards = ReadItems<FeatureCard>(model.Features);
        await Assert.That(cards.Length).IsEqualTo(RowWidth);
        await Assert.That(Array.TrueForAll(cards, static card =>
            card.Name.Length > 0 && card.Category.Length > 0 && card.Description.Length > 0 && card.LiveUse.Length > 0)).IsTrue();
        await Assert.That(model.TargetRate).IsEqualTo(DefaultRate);
        await Assert.That(model.SelectedVenue).IsEqualTo("LSE");
        await Assert.That(model.SearchText).IsEqualTo(string.Empty);
        await Assert.That(model.OnlyAlerts).IsFalse();
    }

    /// <summary>Rejects a missing injected clock before creating subscriptions.</summary>
    /// <returns>A task representing the asynchronous test.</returns>
    [Test]
    public async Task Constructor_NullClock_Throws() =>
        await Assert.That(static () => new MainWindowViewModel(null!)).Throws<ArgumentNullException>();

    /// <summary>Publishes pause and resume state together with dependent command notifications.</summary>
    /// <returns>A task representing the asynchronous test.</returns>
    [Test]
    public async Task StartPauseCommand_Toggled_UpdatesStateAndAvailability()
    {
        using var model = new MainWindowViewModel(new FixedTimeProvider());
        List<string?> properties = [];
        model.PropertyChanged += (_, args) => properties.Add(args.PropertyName);
        var notifications = 0;
        model.StepCommand.CanExecuteChanged += (_, _) => notifications++;
        model.StartPauseCommand.Execute(null);
        var pausedStatus = model.StatusText;
        var pausedLabel = model.StartPauseText;
        var pausedOperation = model.LastOperation;
        var pausedCanStep = model.StepCommand.CanExecute(null);
        model.StartPauseCommand.Execute(null);
        var resumedStatus = model.StatusText;
        var resumedOperation = model.LastOperation;
        var resumedCanStep = model.StepCommand.CanExecute(null);
        model.StartPauseCommand.Execute(null);
        await Assert.That(pausedStatus).IsEqualTo("PAUSED · views remain queryable");
        await Assert.That(pausedLabel).IsEqualTo("Resume");
        await Assert.That(pausedOperation).IsEqualTo("Continuous producer paused");
        await Assert.That(pausedCanStep).IsTrue();
        await Assert.That(resumedCanStep).IsFalse();
        await Assert.That(resumedStatus).IsEqualTo("LIVE · worker ingesting full-rate batches");
        await Assert.That(resumedOperation).IsEqualTo("Continuous producer resumed");
        await Assert.That(properties.Contains(nameof(MainWindowViewModel.IsRunning))).IsTrue();
        await Assert.That(properties.Contains(nameof(MainWindowViewModel.StartPauseText))).IsTrue();
        await Assert.That(notifications).IsEqualTo(ToggleCount);
        await Assert.That(model.EventsPerSecond).IsEqualTo(0D);
        await Assert.That(model.UiFramesPerSecond).IsEqualTo(0D);
    }

    /// <summary>Rounds rates to supported thousand-event presets without redundant notifications.</summary>
    /// <param name="requested">The requested UI rate.</param>
    /// <param name="expected">The rounded and clamped producer rate.</param>
    /// <returns>A task representing the asynchronous test.</returns>
    [Test]
    [Arguments(-1, 1_000)]
    [Arguments(1_999, 1_000)]
    [Arguments(17_999, 17_000)]
    [Arguments(int.MaxValue, 100_000)]
    public async Task TargetRate_Set_RoundsAndClamps(int requested, int expected)
    {
        using var model = CreatePausedModel();
        var notifications = 0;
        model.PropertyChanged += (_, args) =>
        {
            if (args.PropertyName != nameof(MainWindowViewModel.TargetRate))
            {
                return;
            }

            notifications++;
        };
        model.TargetRate = requested;
        model.TargetRate = requested;
        await Assert.That(model.TargetRate).IsEqualTo(expected);
        await Assert.That(notifications).IsEqualTo(1);
        await Assert.That(model.LastOperation.Contains("Producer target changed", StringComparison.Ordinal)).IsTrue();
    }

    /// <summary>Projects one paused frame into all views, the price matrix and stream diagnostics.</summary>
    /// <returns>A task representing the asynchronous test.</returns>
    [Test]
    public async Task StepCommand_Paused_ProjectsMarketFrame()
    {
        using var model = CreatePausedModel();
        model.TargetRate = StepRate;
        model.StepCommand.Execute(null);
        DrainDispatcher();
        var tape = ReadItems<InstrumentSnapshot>(model.LiveTape);
        var rows = ReadItems<MatrixRow>(model.MatrixRows);
        var streams = ReadItems<StreamEvent>(model.StreamEvents);
        await Assert.That(tape.Length).IsEqualTo(InstrumentCount);
        await Assert.That(model.TotalEvents).IsEqualTo((long)RawFrameCount);
        await Assert.That(model.SourceCount).IsEqualTo(InstrumentCount);
        await Assert.That(model.VisibleCount).IsEqualTo(InstrumentCount);
        await Assert.That(model.ViewBacklogCount).IsEqualTo(0);
        await Assert.That(model.HotTickCount).IsEqualTo(RawFrameCount);
        await Assert.That(model.HotDictionaryCount).IsEqualTo(InstrumentCount);
        await Assert.That(model.QuaternaryListCount).IsEqualTo(InstrumentCount);
        await Assert.That(model.QuaternaryDictionaryCount).IsEqualTo(InstrumentCount);
        await Assert.That(model.ReactiveListVersion).IsGreaterThan(0L);
        await Assert.That(model.GenerationMilliseconds).IsGreaterThan(0D);
        await Assert.That(model.AllocatedKilobytesPerFrame).IsGreaterThanOrEqualTo(0D);
        var expectedAlerts = Array.FindAll(tape, static snapshot => snapshot.IsAlert);
        await Assert.That(model.AlertCount).IsEqualTo(expectedAlerts.Length);
        await Assert.That(model.Alerts).IsEquivalentTo(expectedAlerts);
        await Assert.That(model.SlowestUpdates).IsEquivalentTo(tape);
        for (var i = 1; i < model.SlowestUpdates.Count; i++)
        {
            await Assert.That(model.SlowestUpdates[i - 1].LatencyMilliseconds)
                .IsGreaterThanOrEqualTo(model.SlowestUpdates[i].LatencyMilliseconds);
        }

        await Assert.That(model.SectorGroups.Count).IsEqualTo(SectorCount);
        await Assert.That(model.IndexedVenueSnapshots.Count).IsEqualTo(RowWidth);
        await Assert.That(model.IndexedVenueDictionary.Count).IsEqualTo(RowWidth);
        await Assert.That(Array.Exists(streams, static item => item.Source == "Connect() ChangeSet" && item.Detail == "ChangeSet projection")).IsTrue();
        await Assert.That(Array.Exists(streams, static item => item.Detail == "Pooled batch notification")).IsTrue();
        await Assert.That(Array.Exists(streams, static item => item.Detail == "Single cache notification")).IsTrue();
        await Assert.That(Array.TrueForAll(streams, static item => item.Time == "12:34:56.000" && item.Count > 0)).IsTrue();
        for (var row = 0; row < rows.Length; row++)
        {
            var total = 0D;
            var minimum = double.MaxValue;
            var maximum = double.MinValue;
            for (var column = 0; column < RowWidth; column++)
            {
                var price = tape[(row * RowWidth) + column].Price;
                total += price;
                minimum = Math.Min(minimum, price);
                maximum = Math.Max(maximum, price);
            }

            await Assert.That(rows[row].Average).IsEqualTo(total / RowWidth);
            await Assert.That(rows[row].Minimum).IsEqualTo(minimum);
            await Assert.That(rows[row].Maximum).IsEqualTo(maximum);
            await Assert.That(rows[row].Values.Length).IsGreaterThan(0);
        }

        await Assert.That(model.LastOperation).IsEqualTo("Single projection frame generated from 1,000 events");
    }

    /// <summary>Matches symbols, sectors and venues case-insensitively and trims whitespace.</summary>
    /// <param name="search">The dynamic search query.</param>
    /// <param name="expected">The expected count within a complete instrument frame.</param>
    /// <returns>A task representing the asynchronous test.</returns>
    [Test]
    [Arguments(" rl01 ", 1)]
    [Arguments("technology", 8)]
    [Arguments("xnas", 10)]
    [Arguments("missing", 0)]
    [Arguments("", 40)]
    public async Task SearchText_Query_RebuildsDynamicView(string search, int expected)
    {
        using var model = CreatePausedModel();
        model.StepCommand.Execute(null);
        DrainDispatcher();
        model.SearchText = search;
        model.SearchText = search;
        DrainDispatcher();
        var resultCount = model.SearchResults.Count;
        model.OnlyAlerts = true;
        DrainDispatcher();
        var alerts = ReadItems<InstrumentSnapshot>(model.SearchResults);
        model.OnlyAlerts = false;
        DrainDispatcher();
        await Assert.That(resultCount).IsEqualTo(expected);
        await Assert.That(Array.TrueForAll(alerts, static snapshot => snapshot.IsAlert)).IsTrue();
        await Assert.That(model.SearchResults.Count).IsEqualTo(expected);
        await Assert.That(model.LastOperation).IsEqualTo("Dynamic view predicate updated");
    }

    /// <summary>Switches both secondary-index projections together and avoids duplicate property changes.</summary>
    /// <returns>A task representing the asynchronous test.</returns>
    [Test]
    public async Task SelectedVenue_Changed_SwitchesBothIndexViews()
    {
        using var model = CreatePausedModel();
        model.StepCommand.Execute(null);
        DrainDispatcher();
        var notifications = 0;
        model.PropertyChanged += (_, args) =>
        {
            if (args.PropertyName != nameof(MainWindowViewModel.SelectedVenue))
            {
                return;
            }

            notifications++;
        };
        model.SelectedVenue = "XNYS";
        model.SelectedVenue = "XNYS";
        DrainDispatcher();
        await Assert.That(model.IndexedVenueSnapshots.Count).IsEqualTo(RowWidth);
        await Assert.That(Array.TrueForAll(ReadItems<InstrumentSnapshot>(model.IndexedVenueSnapshots), static snapshot => snapshot.Venue == "XNYS")).IsTrue();
        await Assert.That(Array.TrueForAll(ReadItems<KeyValuePair<int, InstrumentSnapshot>>(model.IndexedVenueDictionary), static pair => pair.Value.Venue == "XNYS")).IsTrue();
        await Assert.That(notifications).IsEqualTo(1);
        await Assert.That(model.LastOperation).IsEqualTo("Dynamic secondary index switched to XNYS");
    }

    /// <summary>Bounds historical tape and diagnostics during repeated manual bursts.</summary>
    /// <returns>A task representing the asynchronous test.</returns>
    [Test]
    public async Task BurstCommand_Repeated_BoundsRetainedCollections()
    {
        using var model = CreatePausedModel();
        model.TargetRate = RawFrameCount;
        for (var i = 0; i < BurstCount; i++)
        {
            model.BurstCommand.Execute(null);
            DrainDispatcher();
        }

        await Assert.That(model.TotalEvents).IsEqualTo((long)BurstCount * RawFrameCount);
        await Assert.That(model.LiveTape.Count).IsEqualTo(TapeLimit);
        await Assert.That(model.SourceCount).IsEqualTo(TapeLimit);
        await Assert.That(model.QuaternaryDictionaryCount).IsEqualTo(InstrumentCount);
        await Assert.That(model.QuaternaryListCount).IsLessThanOrEqualTo(IndexedLimit);
        await Assert.That(ReadItems<StreamEvent>(model.StreamEvents).Length).IsEqualTo(StreamLimit);
        await Assert.That(model.LastOperation.StartsWith("Burst generated 1,000 events", StringComparison.Ordinal)).IsTrue();
    }

    /// <summary>Clears projected collections and counters while retaining the matrix shape.</summary>
    /// <returns>A task representing the asynchronous test.</returns>
    [Test]
    public async Task ResetCommand_AfterStep_ClearsProjections()
    {
        using var model = CreatePausedModel();
        model.StepCommand.Execute(null);
        DrainDispatcher();
        model.ResetCommand.Execute(null);
        DrainDispatcher();
        await Assert.That(model.LiveTape.Count).IsEqualTo(0);
        await Assert.That(model.SearchResults.Count).IsEqualTo(0);
        await Assert.That(model.Alerts.Count).IsEqualTo(0);
        await Assert.That(model.SlowestUpdates.Count).IsEqualTo(0);
        await Assert.That(model.SectorGroups.Count).IsEqualTo(0);
        await Assert.That(model.IndexedVenueSnapshots.Count).IsEqualTo(0);
        await Assert.That(model.IndexedVenueDictionary.Count).IsEqualTo(0);
        await Assert.That(model.TotalEvents).IsEqualTo(0L);
        await Assert.That(model.SourceCount).IsEqualTo(0);
        await Assert.That(model.VisibleCount).IsEqualTo(0);
        await Assert.That(model.AlertCount).IsEqualTo(0);
        await Assert.That(model.ReactiveListVersion).IsEqualTo(0L);
        await Assert.That(model.QuaternaryListCount).IsEqualTo(0);
        await Assert.That(model.QuaternaryDictionaryCount).IsEqualTo(0);
        await Assert.That(model.MatrixCellCount).IsEqualTo(InstrumentCount);
        await Assert.That(Array.TrueForAll(ReadItems<MatrixRow>(model.MatrixRows), static row =>
            row.Values.Length == 0 && row.Average == 0 && row.Minimum == 0 && row.Maximum == 0)).IsTrue();
        await Assert.That(model.LastOperation).IsEqualTo("All live collections reset without abandoning pooled hot-path storage");
    }

    /// <summary>Ignores pending UI projections after repeat disposal.</summary>
    /// <returns>A task representing the asynchronous test.</returns>
    [Test]
    public async Task Dispose_PendingFrame_DoesNotApplyUiProjection()
    {
        var model = CreatePausedModel();
        model.StepCommand.Execute(null);
        model.Dispose();
        model.Dispose();
        DrainDispatcher();
        await Assert.That(model.TotalEvents).IsEqualTo(0L);
    }

    /// <summary>Publishes sampled throughput after continuous producer frames reach the dispatcher.</summary>
    /// <param name="cancellationToken">Stops the dispatcher frame if the test is cancelled.</param>
    /// <returns>A task representing the asynchronous test.</returns>
    [Test]
    [Timeout(10_000)]
    public async Task ContinuousProducer_MetricNotification_PublishesRates(CancellationToken cancellationToken)
    {
        using var model = new MainWindowViewModel();
        var frame = new DispatcherFrame();
        await using var cancellation = cancellationToken.Register(
            static state => ((DispatcherFrame)state!).Continue = false,
            frame);
        model.PropertyChanged += (_, args) =>
        {
            if (args.PropertyName != nameof(MainWindowViewModel.UiFramesPerSecond))
            {
                return;
            }

            frame.Continue = false;
        };
        Dispatcher.PushFrame(frame);
        var eventsPerSecond = model.EventsPerSecond;
        var framesPerSecond = model.UiFramesPerSecond;
        model.StartPauseCommand.Execute(null);
        await Assert.That(eventsPerSecond).IsGreaterThan(0D);
        await Assert.That(framesPerSecond).IsGreaterThan(0D);
        await Assert.That(model.TotalEvents).IsGreaterThan(0L);
        await Assert.That(model.SourceCount).IsGreaterThan(0);
    }

    /// <summary>Normalizes a null search and avoids rebuilding an unchanged alert predicate.</summary>
    /// <returns>A task representing the asynchronous test.</returns>
    [Test]
    public async Task SearchText_Null_NormalizesToEmpty()
    {
        using var model = CreatePausedModel();
        model.SearchText = "RL01";
        model.SearchText = null!;
        model.OnlyAlerts = false;
        model.OnlyAlerts = true;
        var lastOperation = model.LastOperation;
        model.OnlyAlerts = true;
        await Assert.That(model.SearchText).IsEqualTo(string.Empty);
        await Assert.That(model.LastOperation).IsEqualTo(lastOperation);
        await Assert.That(model.OnlyAlerts).IsTrue();
    }

    /// <summary>Constructs a paused instance with stable diagnostic timestamps.</summary>
    /// <returns>The owned view model.</returns>
    private static MainWindowViewModel CreatePausedModel()
    {
        var model = new MainWindowViewModel(new FixedTimeProvider());
        model.StartPauseCommand.Execute(null);
        DrainDispatcher();
        return model;
    }

    /// <summary>Processes all queued projection work before the low-priority sentinel.</summary>
    private static void DrainDispatcher()
    {
        var frame = new DispatcherFrame();
        _ = Dispatcher.CurrentDispatcher.BeginInvoke(DispatcherPriority.ApplicationIdle, () => frame.Continue = false);
        Dispatcher.PushFrame(frame);
    }

    /// <summary>Copies a UI-facing non-generic sequence for stable assertions.</summary>
    /// <typeparam name="T">The projected item type.</typeparam>
    /// <param name="items">The dispatcher-owned sequence.</param>
    /// <returns>The projected items in source order.</returns>
    private static T[] ReadItems<T>(System.Collections.IEnumerable items)
    {
        List<T> result = [];
        foreach (T item in items)
        {
            result.Add(item);
        }

        return result.ToArray();
    }
}
